# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84e0b9a96d847e1cbe617e0ec1dafdbc3ee32c98523ddac79acf1e4d37c4d37ebdbcaa2fdd1c510fbfbfbbcc640d89ae9587ab0c1150b6cf0133a3d5924ba5bc
  facebook_app_id: 143699736074360
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>

test:
  secret_key_base: 470bd3a0c78c0f606fb48785aef83246d0e72b7ddf451c11eab55f994bc4b1c980e9577b4c8e78d5079559425c2bd91af3e1bc8e94107933991c8cc6dd23db50
  facebook_app_id: 143699736074360
  facebook_app_secret: <%= ENV['FACEBOOK_APP_SECRET'] %>


# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
